apiVersion: v1
kind: Service
metadata:
  name: transaction-statistics
spec:
  type: NodePort   # 👉 permite expor via minikube service
  selector:
    app: transaction-statistics
  ports:
    - port: 80         # porta interna do service (cluster)
      targetPort: 8080 # porta do container
      nodePort: 30080  # porta fixa no minikube (http://<minikube-ip>:30080)